---
title: STA 331 2.0 Stochastic Processes
subtitle: 7. Poisson processes (cont.) 
author: Dr Thiyanga S. Talagala
date: ""
institute: Department of Statistics, University of Sri Jayewardenepura
output: binb::metropolis
fontsize: 12pt
header-includes:
   - \usepackage{amsfonts}
   - \usepackage{mathrsfs}
---

```{r,setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

## Thinning/ Splitting of a Poisson process

- Thinning or splitting a Poisson process refers to classifying each event, independently, into one of two types: type I and type II. 

    - The arrivals are radioactive emissions and each emitted particle is either detected (type 1) or missed (type 0) by a counter.
    - The arrivals are customers at a service station and each customer is classified as either male (type 1) or female (type 0).

We want to consider the type 1 and type 0 events separately. Due to this, the new random process is usually referred to as thinning or splitting the original Poisson process.

---

## Thinning/ Splitting of a Poisson process - Proposition 

Consider a Poisson Process $\{N(t); t \geq 0 \}$  having rate $\lambda$, and suppose that each time an event
occurs it is classified as either a type I or type II event. Suppose that each event is classified as
type I event with probability $p$ and a type II event with probability $1-p$ independently of all
other events. Let $N_1(t)$ and $N_2(t)$ denote respectively the number of type $I$ and type $II$ events
occurring in $[0, t]$. Then, $\{N_1(t); t \geq 0\}$ and $\{N_2(t); t \geq 0\}$ are both Poisson processes having
respective rate $\lambda p$ and $\lambda (1-p)$. Furthermore, the two processes are independent.

Proof: In-class


---

## Proof



---

## Proof


---

## Proof


---

## Example 1:

If tourists to area A arrive at a Poisson rate of 10 per day, and if each tourist is European with
probability 0.4, what is the probability that more than 20 European tourist will arrive to area A
during next week?


---

## 

---

##

---

## Example 2: 

Customers arrive at a bank at the rate of 10 per hour. Each is either new or
existing customer with probability 0.5. Assume that you know that exactly 10 new customers entered within some
hour (say, 10 to 11am). (a) Compute the probability that exactly 10 existing customers also entered. (b)
Compute the probability that at least 20 customers have entered.


---

##

---

##



---

## Compound Poisson Process

A stochastic process $\{X(t), t\geq 0\}$ is said to be a **compound Poisson process** if it can be represented as

$$X(t) = \sum_{i=1}^{N(t)}Y_i, \text{ } t \geq 0$$

where $\{ N(t), t \geq 0\}$ is a Poisson process, and $\{Y_i, i \geq 1\}$ is a family of independent and identically distributed random variables that is also independent of $\{N(t), t\ge 0\}$. The $X(t)$ is said to be a **compound Poisson random** variable.


---

## Examples of Compound Poisson Processes

Suppose customers leave a supermarket in accordance with a Poisson process. If the $Y_i$, the amount spent by the $i$th customer, $i=1, 2, ...$ are independent and identically distributed, then $\{X(t), t \geq 0\}$ is a compound Poisson process where $X(t)$  denotes the total amount of money spent by time $t$. 

---

## Examples of Compound Poisson Processes (cont.)

Suppose that buses arrive at a picketing event in accordance with a Poisson process, and suppose that the numbers of passengers in each bus are assumed to be independent and identically distributed. Then $[X(t), t \geq 0]$  is a compound Poisson process where $X(t)$ denotes the number of passengers who have arrived by $t$. The $Y_i$  represents the number of passengers in the $i$th bus.

---

## Examples of Compound Poisson Processes (cont.)

$$X(t) = \sum_{i=1}^{N(t)}Y_i, \text{ } t \geq 0$$

If $Y_i \equiv 1$, then $X(t) = N(t)$, and so we have the usual Poisson process.


---

### Compound Poisson Process

A stochastic process $\{X(t), t\geq 0\}$ is said to be a **compound Poisson process** if it can be represented as

$$X(t) = \sum_{i=1}^{N(t)}Y_i, \text{ } t \geq 0$$

where $\{ N(t), t \geq 0\}$ is a Poisson process, and $\{Y_i, i \geq 1\}$ is a family of independent and identically distributed random variables that is also independent of $\{N(t), t\ge 0\}$. The $X(t)$ is said to be a **compound Poisson random** variable.

Because $X(t)$ is a compound Poisson variable with Poisson parameter $\lambda t$ we can show that,

$E[X(t)] = \lambda t E(Y_1)$ and $Var[X(t)] = \lambda t E[Y_1^2].$


---

##


---

## Example

Suppose that families migrate to an area at a Poisson rate lambda = 2 per week. The number of people in each family is independent and takes on values 1, 2, 3, 4 with respective probabilities 1/6, 1/3, 1/3, 1/6. Find the expected value and variance of the number of individuals migrating to this area during a fixed five week period. (Introduction to Probability Models by Sheldon M. Ross)


---

##


---

## Non-homogeneous Poisson Process

- Similar to an ordinary Poisson process, except that the average rate of arrivals is allowed to vary with time.

    - Homogeneous Poisson process: constant arrival rate $\lambda$.

    - Non-Homogeneous Poisson process: time varying arrival rate $\lambda(t)$. 

- Relaxes the Poisson process assumption of **stationary increments**. 

- The intensity function $\lambda(t)$ of a nonhomogeneous Poisson process can vary with time (deterministic function of $t$).

For example, the arrival rate of students to the cafeteria is larger during lunch time compared to, say, 4 p.m.


---

## Stationary increments. 

To call the increments stationary means that the probability distribution of any increment $X_t$ − $X_s$ depends only on the length t − s of the time interval.

Note that in a Poisson process, the distribution of the number of arrivals in any interval depends only on the length of the interval, and not on the exact location of the interval on the real line. Therefore the Poisson process has stationary increments.

---

## Nonhomogeneous Poisson Process

A non-homogeneous Poisson process is obtained by allowing the arrival rate at
time $t$ to be a function of $t$.

The counting process $\{N(t): t \geq 0\}$ is said to be a nonhomogeneous Poisson process with intensity
function $\lambda(t), t >0$ if

1. $N(0) = 0$,

2. The process has independent increments,

3. 

\begin{math}
 P[N(t+h)-N(t) = k]=\left\{
    \begin{array}{ll}
      \lambda (t) h + o(h), & \mbox{k=1}\\
      o(h), & k \geq 2 \\
      1-\lambda (t) h + o(h), & k = 0 \\
    \end{array}
  \right.
\end{math}

---

## Theorem

Let $\{N(t): t >0\}$ be a nonhomogeneous Poisson process with intensity function $\lambda(t)$. Then,

$$P[N(t+s) - N(t)=n]=\frac{e^{-[m(t+s) - m(t)]}[m(t+s)-m(t)]^n}{n!}$$

where 

$$m(t) = \int_0^t \lambda(u)du.$$


---

## Proof - Inclass

---

## Proof

---

## Proof

---

## Proof


---

### Note

In homogeneous Poisson process

$$P_n(t) = P[N(t)=n]$$

In Non-homogeneous Poisson process

$$P_{n, t}(s) = P[N(t+s)-N(t)=n]$$

$n$ - number of events

$t$ - starting time

$s$ - length of the interval.

---

## Example

A group of entrepreneurs runs a clothing store which opens at 8 A.M. From 8 until 11 A.M. customers arrive, on
the average, at a steady increase rate that starts with an initial rate of 5 customers per hour
at 8 A.M. and reaches a maximum of 20 customers per hour at 11 A.M. From 11 A.M. until 1
P.M. the average rate seems to remain constant at 20 customers per hour. However, the average
arrival rate then drops steadily from 1 P.M. until closing time at 5 P.M. at which time it has
the value of 12 customers per hour. If we assume that the number of customers arriving at
the clothing store during disjoint time periods is independent, then what is the probability
that no customers arrive between 8:30 A.M. and 9:30 A.M. on Monday morning? What is the
expected number of arrivals in this period?


---

## Solution

---

## Solution

---

## Acknowledgement

The contents in the slides are based on 

Introduction to Probability Models by Sheldon M. Ross.

